id: P51D4CBF5
initial_creation_type: ocr
source_metadata:
  volumes:
    8e889a15a92e43ba937394ec4c7a80be:
      base_file: v042.txt
      image_group_id: I1PD95887
      title: ''
      total_pages: 1712
      volume_number: 42
